### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by xanxanxan** [sritterbusch/ospac#1]
First of all: The project looks very promising and I’m impatient to try it. But during the make process, I got error messages and I can’t use ospac.

xan@xan:~/ospac$ make ospac && sudo make install
cd Release;make all;cd ..
make[1]: Verzeichnis »/home/xan/ospac/Release« wird betreten
Building file: ../src/Analyzer.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Analyzer.d" -MT"src/Analyzer.o" -o "src/Analyzer.o" "../src/Analyzer.cpp"
Finished building: ../src/Analyzer.cpp

Building file: ../src/Channel.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Channel.d" -MT"src/Channel.o" -o "src/Channel.o" "../src/Channel.cpp"
Finished building: ../src/Channel.cpp

Building file: ../src/CrosstalkFilter.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/CrosstalkFilter.d" -MT"src/CrosstalkFilter.o" -o "src/CrosstalkFilter.o" "../src/CrosstalkFilter.cpp"
Finished building: ../src/CrosstalkFilter.cpp

Building file: ../src/CrosstalkGate.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/CrosstalkGate.d" -MT"src/CrosstalkGate.o" -o "src/CrosstalkGate.o" "../src/CrosstalkGate.cpp"
Finished building: ../src/CrosstalkGate.cpp

Building file: ../src/Equalizer.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Equalizer.d" -MT"src/Equalizer.o" -o "src/Equalizer.o" "../src/Equalizer.cpp"
Finished building: ../src/Equalizer.cpp

Building file: ../src/Frequency.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Frequency.d" -MT"src/Frequency.o" -o "src/Frequency.o" "../src/Frequency.cpp"
Finished building: ../src/Frequency.cpp

Building file: ../src/Log.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Log.d" -MT"src/Log.o" -o "src/Log.o" "../src/Log.cpp"
Finished building: ../src/Log.cpp

Building file: ../src/Maximizer.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Maximizer.d" -MT"src/Maximizer.o" -o "src/Maximizer.o" "../src/Maximizer.cpp"
Finished building: ../src/Maximizer.cpp

Building file: ../src/Merge.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Merge.d" -MT"src/Merge.o" -o "src/Merge.o" "../src/Merge.cpp"
Finished building: ../src/Merge.cpp

Building file: ../src/MonoMix.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/MonoMix.d" -MT"src/MonoMix.o" -o "src/MonoMix.o" "../src/MonoMix.cpp"
Finished building: ../src/MonoMix.cpp

Building file: ../src/OspacMain.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/OspacMain.d" -MT"src/OspacMain.o" -o "src/OspacMain.o" "../src/OspacMain.cpp"
Finished building: ../src/OspacMain.cpp

Building file: ../src/Physics.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Physics.d" -MT"src/Physics.o" -o "src/Physics.o" "../src/Physics.cpp"
Finished building: ../src/Physics.cpp

Building file: ../src/Plot.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Plot.d" -MT"src/Plot.o" -o "src/Plot.o" "../src/Plot.cpp"
../src/Plot.cpp: In static member function ‘static std::vector<std::vector<unsigned int> > Plot::histogramm(const Channel&, unsigned int, unsigned int, unsigned int)’:
../src/Plot.cpp:38:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(value>=sizeY)
             ^
../src/Plot.cpp:40:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(value>=zero)
             ^
../src/Plot.cpp:42:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for(;value>=zero;value--)
                ^
../src/Plot.cpp:50:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for(;value<=zero;value++)
                ^
Finished building: ../src/Plot.cpp

Building file: ../src/SelectiveLeveler.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/SelectiveLeveler.d" -MT"src/SelectiveLeveler.o" -o "src/SelectiveLeveler.o" "../src/SelectiveLeveler.cpp"
Finished building: ../src/SelectiveLeveler.cpp

Building file: ../src/Skip.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Skip.d" -MT"src/Skip.o" -o "src/Skip.o" "../src/Skip.cpp"
Finished building: ../src/Skip.cpp

Building file: ../src/StereoMix.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/StereoMix.d" -MT"src/StereoMix.o" -o "src/StereoMix.o" "../src/StereoMix.cpp"
Finished building: ../src/StereoMix.cpp

Building file: ../src/Wave.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Wave.d" -MT"src/Wave.o" -o "src/Wave.o" "../src/Wave.cpp"
../src/Wave.cpp:15:22: fatal error: sndfile.h: Datei oder Verzeichnis nicht gefunden
  #include <sndfile.h>
                      ^
compilation terminated.
make[1]: **\* [src/Wave.o] Fehler 1
make[1]: Verzeichnis »/home/xan/ospac/Release« wird verlassen
cd Release;make all;cd ..
make[1]: Verzeichnis »/home/xan/ospac/Release« wird betreten
Building file: ../src/Wave.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Wave.d" -MT"src/Wave.o" -o "src/Wave.o" "../src/Wave.cpp"
../src/Wave.cpp:15:22: fatal error: sndfile.h: Datei oder Verzeichnis nicht gefunden
  #include <sndfile.h>
                      ^
compilation terminated.
make[1]: **\* [src/Wave.o] Fehler 1
make[1]: Verzeichnis »/home/xan/ospac/Release« wird verlassen
cd Release;make install;cd ..
make[1]: Verzeichnis »/home/xan/ospac/Release« wird betreten
Building file: ../src/Wave.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Wave.d" -MT"src/Wave.o" -o "src/Wave.o" "../src/Wave.cpp"
../src/Wave.cpp:15:22: fatal error: sndfile.h: Datei oder Verzeichnis nicht gefunden
  #include <sndfile.h>
                      ^
compilation terminated.
make[1]: **\* [src/Wave.o] Fehler 1
make[1]: Verzeichnis »/home/xan/ospac/Release« wird verlassen

I’m a very unexperienced user when it comes to make. So apologies if I made a stupid mistake.

**Comment by sritterbusch** [comment]
Dear Xanxanxan,

thanks for trying ospac. To compile you need two things: A c++-compiler and the libsndfile-Library. What you are missing, is the libsndfile-Library.

On Mac you can install libsnd via http://brew.sh - as soon homebrew is installed, invoke 
`$ brew install libsndfile`

On Linux you have to ask your package manager to install libsndfile. On Debian derivates as root, this will do the trick:
`# apt-get install libsndfile1 libsndfile1-dev`

Good luck! =)

**Comment by xanxanxan** [comment]
Thanks for replying so quickly.
I’m using Ubuntu. The build-essential, g++ and libsndfile1 packages are installed. However, I ran 'gcc -v' and 'make -v' since I read that this needs to be done to install the compilers correctly.
The make process now gives me another error message:

xan@xan:~/ospac$ make ospac && sudo make install
cd Release;make all;cd ..
make[1]: Verzeichnis »/home/xan/ospac/Release« wird betreten
Building file: ../src/Wave.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Wave.d" -MT"src/Wave.o" -o "src/Wave.o" "../src/Wave.cpp"
../src/Wave.cpp:15:22: fatal error: sndfile.h: Datei oder Verzeichnis nicht gefunden
  #include <sndfile.h>
                      ^
compilation terminated.
make[1]: **\* [src/Wave.o] Fehler 1
make[1]: Verzeichnis »/home/xan/ospac/Release« wird verlassen
[sudo] password for xan: 
cd Release;make all;cd ..
make[1]: Verzeichnis »/home/xan/ospac/Release« wird betreten
Building file: ../src/Wave.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Wave.d" -MT"src/Wave.o" -o "src/Wave.o" "../src/Wave.cpp"
../src/Wave.cpp:15:22: fatal error: sndfile.h: Datei oder Verzeichnis nicht gefunden
  #include <sndfile.h>
                      ^
compilation terminated.
make[1]: **\* [src/Wave.o] Fehler 1
make[1]: Verzeichnis »/home/xan/ospac/Release« wird verlassen
cd Release;make install;cd ..
make[1]: Verzeichnis »/home/xan/ospac/Release« wird betreten
Building file: ../src/Wave.cpp
Invoking: Cross G++ Compiler
g++ -I/usr/local/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Wave.d" -MT"src/Wave.o" -o "src/Wave.o" "../src/Wave.cpp"
../src/Wave.cpp:15:22: fatal error: sndfile.h: Datei oder Verzeichnis nicht gefunden
  #include <sndfile.h>
                      ^
compilation terminated.
make[1]: **\* [src/Wave.o] Fehler 1
make[1]: Verzeichnis »/home/xan/ospac/Release« wird verlassen

From what I understand, make doesn’t find libsndfile. But 'dpkg -s libsndfile1’ says: 'Status: install ok installed'. What am I doing wrong?

**Comment by sritterbusch** [comment]
On Linux, there are two packages: libsndfile1 and libsndfile1-dev. Please check for both.

**Comment by xanxanxan** [comment]
The -dev package was missing. Thank you very much for walking me through. I’m happy to start mixing the episode now!
